# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f3d9726f5bbf92269279924631694febc4f161d17d600a8c821e9efde2715f4a7329abe4baedb27fb1cf7c5e74e90bfd673b069902a7e927a13e498bc2857ee

test:
  secret_key_base: 3fedd35ac7809429c74a8fe6a7feb9706451fff3fe9d762db3cde410e61562a8803132d2152deb5385793eba2b2fd28f50b351c4f5971775538124e446953fbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
